backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: "site/static/img/blog" # Folder where user uploaded files should go
public_folder: "/img/blog"
